src/Entity/CategorieProduit.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategorieProduitRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class CategorieProduit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageCouverture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $courte_introduction;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $courte_description;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\SousCategorieProduit", mappedBy="categorieProduit")
     */
    private $sousCategories;

    public function __construct()
    {
        $this->sousCategories = new ArrayCollection();
    }

    /**
     * Initialise le slug
     *
     * @ORM\PrePersist()
     */
    public function initializeSlug()
    {

        $slugify = new Slugify();
        if (empty($this->slug)) {
            $this->slug = $slugify->slugify($this->libelle);
        }
    }

    public function hasSubCategories() {

        if(count($this->getSousCategories()) > 0)
            return true;

    return false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImageCouverture(): ?string
    {
        return $this->imageCouverture;
    }

    public function setImageCouverture(?string $imageCouverture): self
    {
        $this->imageCouverture = $imageCouverture;

        return $this;
    }

    public function getCourteIntroduction(): ?string
    {
        return $this->courte_introduction;
    }

    public function setCourteIntroduction(string $courte_introduction): self
    {
        $this->courte_introduction = $courte_introduction;

        return $this;
    }

    public function getCourteDescription(): ?string
    {
        return $this->courte_description;
    }

    public function setCourteDescription(string $courte_description): self
    {
        $this->courte_description = $courte_description;

        return $this;
    }

    /**
     * @return Collection|SousCategorieProduit[]
     */
    public function getSousCategories(): Collection
    {
        return $this->sousCategories;
    }

    public function addSousCategory(SousCategorieProduit $sousCategory): self
    {
        if (!$this->sousCategories->contains($sousCategory)) {
            $this->sousCategories[] = $sousCategory;
            $sousCategory->setCategorieProduit($this);
        }

        return $this;
    }

    public function removeSousCategory(SousCategorieProduit $sousCategory): self
    {
        if ($this->sousCategories->contains($sousCategory)) {
            $this->sousCategories->removeElement($sousCategory);
            // set the owning side to null (unless already changed)
            if ($sousCategory->getCategorieProduit() === $this) {
                $sousCategory->setCategorieProduit(null);
            }
        }

        return $this;
    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"libelle"},
 *     message="Un produit portant ce libellé existe déjà !"
 *     )
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $parfume;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SousCategorieProduit", inversedBy="produits")
     */
    private $SousCategorieProduit;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $origine;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $utilisateur;


    /**
     * Initialise le slug
     *
     * @ORM\PrePersist()
     */
    public function initializeSlug()
    {

        $slugify = new Slugify();
        if (empty($this->slug)) {
            $this->slug = $slugify->slugify($this->libelle);
        }
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getParfume(): ?bool
    {
        return $this->parfume;
    }

    public function setParfume(?bool $parfume): self
    {
        $this->parfume = $parfume;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getSousCategorieProduit(): ?SousCategorieProduit
    {
        return $this->SousCategorieProduit;
    }

    public function setSousCategorieProduit(?SousCategorieProduit $SousCategorieProduit): self
    {
        $this->SousCategorieProduit = $SousCategorieProduit;

        return $this;
    }

    public function getOrigine(): ?string
    {
        return $this->origine;
    }

    public function setOrigine(?string $origine): self
    {
        $this->origine = $origine;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use App\Entity\SousCategorieProduit;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('libelle',
                TextType::class,
                $this->getConfiguration("Libellé :", "Libellé du produit...")
            )
            ->add('description',
                TextareaType::class,
                $this->getConfiguration("Description : ", "Description du produit...")
            )
            ->add("prix",
                MoneyType::class,
                $this->getConfiguration("Prix : ", "Prix du produit...")
            )
            ->add('image',
                UrlType::class,
                $this->getConfiguration("Image : ", "Liens vers l'image")
            )
            ->add('SousCategorieProduit',
                EntityType::class, [
                    'class' => SousCategorieProduit::class,
                    'choice_label' => "libelle"
                ]
            )
            ->add('parfume',
                ChoiceType::class,
                [
                    'label' => "Parfum :",
                    'choices' => [
                        'Nature' => false,
                        'Parfumé' => true,
                        'Ce produit ne concerne pas les parfums' => null //A gérer en ajax dans le futur en se basant sur la propriété "hasParfume" de la sous-catégorie, pas les compétences requises au moment fait.
                    ],

                    'empty_data' => null
                ]
            )
            ->add('origine',
                TextType::class,
                $this->getConfiguration("Origine :", "Origine du produit")
            );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProductsController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Entity\SousCategorieProduit;
use App\Repository\SousCategorieProduitRepository;
use App\Service\Menu;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProductsController extends AbstractController
{

    /**
     * Permet d'afficher les produits par leur sous-catégorie et par le filtre "parfumés"
     *
     * @Route("/{slug}/produits/parfume={parfume}", name="show_by_parfume")
     *
     * @param SousCategorieProduitRepository $repo
     * @param Menu $menu
     * @param $slug
     * @param $parfume
     * @return Response
     */
    public function showByParfume(SousCategorieProduitRepository $repo, Menu $menu, $slug, $parfume)
    {

        return $this->render("products/show_by_parfume.html.twig",[
            'menu' => $menu,
            'sousCategorie' => $repo->findBySlugAndParfume($slug,$parfume),
            'parfume' => $parfume
        ]);

    }

    /**
     * Permet d'afficher la liste des produits par sous-categorie
     *
     * @Route("/{slug}/produits", name="show_by_sousCategorie")
     *
     * @param SousCategorieProduit $sousCategorie
     * @param Menu $menu
     * @return Response
     */
    public function showBySousCategorie(SousCategorieProduit $sousCategorie, Menu $menu) {

        return $this->render("products/show_by_sousCategorie.html.twig",[
            'menu' => $menu,
            'sousCategorie' => $sousCategorie
        ]);

    }

    /**
     * Permet d'afficher les détails d'un produit
     *
     * @Route("/produit/{slug}", name="show_product")
     *
     * @param Menu $menu
     * @param Produit $produit
     * @return Response
     */
    public function showProduct(Menu $menu, Produit $produit) {

        return $this->render('products/show_product.html.twig',[
           'menu' => $menu,
           'produit' => $produit
        ]);
    }

}

templates/products/show_by_parfume.html.twig
{% extends 'base.html.twig' %}

{% block title %} Nos {{ sousCategorie.libelle }} {% endblock %}

{% block body %}
    {{ menu.render }}

    <main>
        <!-- PAGE INFO -->
        <section class="page-info set-bg" data-bg="{{ sousCategorie.imageCouverture }}">
            <div class="section-header">
                <h1 class="text-white">
                    Nos
                    {% if parfume and sousCategorie.hasNatureParfume %}
                        {{ sousCategorie.libelle }} parfumés
                    {% else %}
                        {{ sousCategorie.libelle }}
                    {% endif %}

                </h1>
                <span>~ {{ sousCategorie.courteDescription }} ~</span>
            </div>
        </section>

        <!-- SHOP LIST -->
        <section class="section-primary pt-150 pb-113 shop-list">
            <div class="container">
                <div class="row products">

                        {% for product in sousCategorie.produits %}
                            {% include 'partials/_products.html.twig' %}
                        {% endfor %}
                </div>
            </div>

            <div class="woocommerce-pagination justify-content-center">
                <ul class="page-numbers">
                    <li>
                        <a href="#" class="page-numbers prev">
                            <span class="lnr lnr-arrow-left"></span>
                        </a>
                    </li>
                    <li>
                        <span class="page-numbers current">1</span>
                    </li>
                    <li>
                        <a href="#" class="page-numbers inactive">
                            2
                        </a>
                    </li>
                    <li>
                        <a href="#" class="page-numbers inactive">
                            3
                        </a>
                    </li>
                    <li>
                        <a href="#" class="page-numbers next">
                            <span class="lnr lnr-arrow-right"></span>
                        </a>
                    </li>
                </ul>
            </div>
        </section>
    </main>

{% endblock %}

templates/products/show_by_sousCategorie.html.twig
{% extends 'base.html.twig' %}

{% block title %} Nos {{ sousCategorie.libelle }} {% endblock %}

{% block body %}
    {{ menu.render }}

    <main>
        <!-- PAGE INFO -->
        <section class="page-info set-bg" data-bg="{{ sousCategorie.imageCouverture }}">
            <div class="section-header">
                <h1 class="text-white">
                    Nos {{ sousCategorie.libelle }}
                </h1>

                <span>~ {{ sousCategorie.courteDescription }} ~</span>
            </div>
        </section>

        <!-- SHOP LIST -->
        <section class="section-primary pt-150 pb-113 shop-list">
            <div class="container">
                <div class="row products">

                    {% for product in sousCategorie.produits %}
                        {% include 'partials/_products.html.twig' %}
                    {% endfor %}

                </div>
            </div>

            <div class="woocommerce-pagination justify-content-center">
                <ul class="page-numbers">
                    <li>
                        <a href="#" class="page-numbers prev">
                            <span class="lnr lnr-arrow-left"></span>
                        </a>
                    </li>
                    <li>
                        <span class="page-numbers current">1</span>
                    </li>
                    <li>
                        <a href="#" class="page-numbers inactive">
                            2
                        </a>
                    </li>
                    <li>
                        <a href="#" class="page-numbers inactive">
                            3
                        </a>
                    </li>
                    <li>
                        <a href="#" class="page-numbers next">
                            <span class="lnr lnr-arrow-right"></span>
                        </a>
                    </li>
                </ul>
            </div>
        </section>
    </main>

{% endblock %}

templates/products/show_product.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ produit.libelle }}{% endblock %}

{% block body %}
    {{ menu.render }}

    <main>
        <!-- PAGE BREADCRUMB -->
        <section class="page-breadcrumb">
            <div class="container">
                <div class="row justify-content-between align-content-center">
                    <div class="col-md-auto">
                        <h3>{{ produit.libelle }}</h3>
                    </div>
                </div>
            </div>
        </section>

        <!-- PROJECT -->
        <section class="section-primary project pt-120 pb-120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7">
                        <div class="project-image">
                            <div class="image-holder">
                                <img src="{{ produit.image }}" alt="image du produit {{ produit.libelle }}">
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="project-content">
                            <h4>Description :</h4>
                            <p>{{ produit.description }}</p>
                            <div class="info">
                                <div class="info-item">
                                    <h4>prix :</h4>
                                    <span>{{ produit.prix }} &euro;</span>
                                </div>

                                <div class="info-item">
                                    <h4>Catégorie du produit : </h4>
                                    <span>{{ produit.sousCategorieProduit.libelle }}</span>
                                </div>

                                <div class="info-item">
                                    <h4> Origine : </h4>
                                    <span>{{ produit.origine }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}